{:user {:deploy-repositories [["clojars" {:url "https://clojars.org/repo"
                                          :creds :gpg}]]
        :dependencies [[spyscope "0.1.2"]]
        :injections [(require 'spyscope.core)
                     (require 'clojure.pprint)]
        :plugins [[lein-difftest "1.3.8"]
                  [lein-clojars "0.9.1"]
                  [lein-marginalia "0.7.1"]
                  [lein-pprint "1.1.1"]
                  [lein-swank "1.4.4"]
                  [lein-kibit "0.0.8" :exclusions [org.clojure/clojure]]
                  [lein-bikeshed "0.1.0"]
                  [lein-midje "2.0.1"]
                  [lein-midje-lazytest "0.1.0" :exclusions [org.clojure/clojure]]
                  [lazytest "1.2.3"]
                  [lein-expectations "0.0.7"]
                  [lein-autoexpect "0.2.2"]
                  [lein-outdated "1.0.0"]
                  [lein-pedantic "0.0.5"]
                  [lein-exec "0.3.0"]
                  [lein-bin "0.3.2"]
                  [org.clojars.strongh/lein-init-script "1.3.1"]
                  [lein-ritz "0.5.0"]]}}
